#pragma once

#include <ntifs.h>

#define IO_GET_CLIENT_ADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)

NTSTATUS IoControl(PDEVICE_OBJECT pDeviceObject, PIRP pIRP);
NTSTATUS CloseCall(PDEVICE_OBJECT pDeviceObject, PIRP pIRP);
NTSTATUS CreateCall(PDEVICE_OBJECT pDeviceObject, PIRP pIRP);

